### ISSUE TITLE
Zabbix elasticsearch jvm.mem.heap_used_in_bytes -> DotMap()

### ISSUE THREAD

**Issue by 4erpak** [untergeek/zabbix-grab-bag#6]
/usr/bin/es_stats_zabbix single nodeinfo[test,jvm.mem.heap_used_in_bytes]
DotMap()
Why did this happen?

**Comment by untergeek** [comment]
What version of Elasticsearch are you using?  And what JVM?  It may be that one or the other may be a culprit.

Seeing `DotMap()` indicates an empty response there.

**Comment by 4erpak** [comment]
java version "1.7.0_71"
Elasticsearch version":"1.7.0
The same error for:
jvm.mem.heap_used_percent
jvm.gc.collectors.old.collection_count
jvm.gc.collectors.old.collection_time_in_millis

**Comment by untergeek** [comment]
I think I know how to make it send ZBX_NOTSUPPORTED when it gets a bad value.

However, I also wonder what JVM arguments you are using.  The fact that no GC old values are there suggests some different JVM tuning arguments.

How are you launching Elasticsearch, and with what JVM arguments?

**Comment by 4erpak** [comment]
I'm using arguments from your ini file:
key20 = nodestats[YOUR_NODE_NAME,process.open_file_descriptors]
key21 = nodestats[YOUR_NODE_NAME,jvm.mem.heap_max_in_bytes]
key22 = nodestats[YOUR_NODE_NAME,jvm.mem.heap_used_in_bytes]
key23 = nodestats[YOUR_NODE_NAME,jvm.mem.heap_used_percent]
key24 = nodestats[YOUR_NODE_NAME,jvm.gc.collectors.old.collection_count]
key25 = nodestats[YOUR_NODE_NAME,jvm.gc.collectors.old.collection_time_in_millis]
i.e. /usr/bin/es_stats_zabbix single nodestats[test,jvm.mem.heap_used_in_bytes]

**Comment by untergeek** [comment]
I understood this.  My point is that these are not showing up for you because of differences in how your JVM was started.  Do you have access to the JVM arguments with which Elasticsearch was started?

**Comment by 4erpak** [comment]
Sorry for misspelling =(
my test VM (single node) with correct output for any  nodestats[*] (based on 
openjdk version "1.8.0_60"
OpenJDK Runtime Environment (build 1.8.0_60-b27)
OpenJDK 64-Bit Server VM (build 25.60-b23, mixed mode)
and ES 1.7.2):
elastic+  5584  2.4 22.2 3191504 226356 ?      Ssl  11:46   0:03 /bin/java -Xms256m -Xmx1g -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Delasticsearch -Des.foreground=yes -Des.path.home=/usr/share/elasticsearch -cp :/usr/share/elasticsearch/lib/elasticsearch-1.7.2.jar:/usr/share/elasticsearch/lib/*:/usr/share/elasticsearch/lib/sigar/* -Des.pidfile=/var/run/elasticsearch/elasticsearch.pid -Des.default.path.home=/usr/share/elasticsearch -Des.default.path.logs=/var/log/elasticsearch -Des.default.path.data=/var/lib/elasticsearch -Des.default.config=/etc/elasticsearch/elasticsearch.yml -Des.default.path.conf=/etc/elasticsearch org.elasticsearch.bootstrap.Elasticsearch

Another host (in cluster) on which it's not works (
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)
and ES 1.6.2
398      17893 84.4 50.9 202854740 7790396 ?   Sl   Sep23 39846:39 /usr/java/default/bin/java -Xms7g -Xmx7g -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Delasticsearch -Des.pidfile=/var/run/elasticsearch/elasticsearch.pid -Des.path.home=/usr/share/elasticsearch -cp :/usr/share/elasticsearch/lib/elasticsearch-1.6.2.jar:/usr/share/elasticsearch/lib/*:/usr/share/elasticsearch/lib/sigar/* -Des.default.path.home=/usr/share/elasticsearch -Des.default.path.logs=/data/elasticsearch/logs -Des.default.path.data=/data/elasticsearch/data -Des.default.path.work=/data/elasticsearch/work -Des.default.path.conf=/etc/elasticsearch org.elasticsearch.bootstrap.Elasticsearch

**Comment by untergeek** [comment]
You may be seeing something different because your cluster is using 1.6.2 and not 1.7.2.

I will run a test against 1.6.x and 1.5.x locally to see what shakes out

**Comment by untergeek** [comment]
While I try to understand why some metrics do not always show up, please run:

``` sh
sudo pip install -U es-stats-zabbix
```

…to get the most recent version.  It will now send `ZBX_NOTSUPPORTED` if no value is found (which apparently happens sometimes).  

I believe that if no value has been propagated, that the results don't have that field yet.  Hence an empty, or 'DotMap()' value.

**Comment by untergeek** [comment]
> `"heap_used_percent":94`

I just barely took a second look at your error, and WHOA!  This should NEVER happen, or be allowed to happen on an Elasticsearch box.  Part of the reason may be:

> `-Xms256m -Xmx1g`

These numbers are exceptionally low, and are suitable only for a non-master, non-data, client-only node.  In fact, those numbers are low even for that.  These are the defaults.  You should increase these numbers to both be the same by starting Elasticsearch with `ES_HEAP_SIZE` set like this:

```
ES_HEAP_SIZE=8g bin/elasticsearch -d
```

…or in `/etc/default/elasticsearch`:

```
# Heap size defaults to 256m min, 1g max
# Set ES_HEAP_SIZE to 50% of available RAM, but no more than 30.5g
ES_HEAP_SIZE=8g
```

**Comment by untergeek** [comment]
Elasticsearch should have enough memory that you have a gentle, saw-tooth pattern to an old-gen garbage collection graph.  The peaks should be between 70% and 75% full, and the valleys should dip to 50% full or lower.  A 90%+ value is bad.

**Comment by untergeek** [comment]
Hi.  I found a bug and updated es-stats-zabbix again.  Please update via:

```
sudo pip install -U es-stats-zabbix
```
