### ISSUE TITLE
Can't import template

### ISSUE THREAD

**Issue by gourlaa** [untergeek/zabbix-grab-bag#7]
Hi ! 

Thanks for your plugin ! :+1: 
My zabbix version is : Zabbix 2.2.2
I have a problem, I can't import the template. I'm getting this message :+1: 

Created: Application "ES Cluster" on "Elasticsearch Cluster".
Created: Item "Cluster Stats Batch Run: $1" on "Elasticsearch Cluster".
Created: Item "Cluster Stats Batch Run: $1" on "Elasticsearch Cluster".
Created: Item "Cluster Stats Batch Run: $1" on "Elasticsearch Cluster".
Created: Item "Elasticsearch Cluster: Documents indexed per second" on "Elasticsearch Cluster".
Created: Item "Elasticsearch Cluster Health: $1" on "Elasticsearch Cluster".
Created: Item "Elasticsearch Cluster Health: $1" on "Elasticsearch Cluster".
Created: Item "Elasticsearch Cluster Health: $1" on "Elasticsearch Cluster".
Created: Item "Elasticsearch Cluster Health: $1" on "Elasticsearch Cluster".
Created: Item "Elasticsearch Cluster Health: $1" on "Elasticsearch Cluster".
Created: Item "Elasticsearch Cluster Health: $1" on "Elasticsearch Cluster".
Created: Item "Elasticsearch Cluster Health: $1" on "Elasticsearch Cluster".
Created: Item "Elasticsearch Cluster Health: $1" on "Elasticsearch Cluster".
Created: Item "Elasticsearch Cluster Health: $1" on "Elasticsearch Cluster".
Created: Item "Elasticsearch Cluster State: $1" on "Elasticsearch Cluster".
Created: Item "Elasticsearch Cluster Stats: $1" on "Elasticsearch Cluster".
Created: Item "Elasticsearch Cluster Stats: $1" on "Elasticsearch Cluster".
Created: Item "Elasticsearch Cluster Stats: $1" on "Elasticsearch Cluster".
Created: Item "Elasticsearch Cluster Stats: $1" on "Elasticsearch Cluster".
Created: Item "Elasticsearch Cluster Stats: $1" on "Elasticsearch Cluster".
Created: Item "Elasticsearch Cluster Stats: $1" on "Elasticsearch Cluster".
Created: Item "Elasticsearch Cluster Stats: $1" on "Elasticsearch Cluster".
Incorrect trigger expression. Check expression part starting from " and {Elasticsearch Cluster:health[number_of_nodes].last()}<{Elasticsearch Cluster:health[number_of_nodes].min(5m)}) or ({TRIGGER.VALUE}=1 and {Elasticsearch Cluster:health[number_of_nodes].last(0)}<{Elasticsearch Cluster:health[number_of_nodes].max(1d)})".

**Comment by untergeek** [comment]
Hmmm.  I guess that this trigger is not 2.2.2-friendly.  I'm not sure what to tell you there.  I can give you a gist with that trigger removed.

**Comment by gourlaa** [comment]
Yes, it could be great. Which trigger will be removed after ?
Do you think that the plugin still usable ?

**Comment by untergeek** [comment]
I added a 2.2 template, with that trigger removed: 

https://github.com/untergeek/zabbix-grab-bag/blob/master/Elasticsearch/es_stats_zabbix_template_2.2.xml

**Comment by untergeek** [comment]
Please report any difficulties with this template.  I'll patch them up quickly.

Also, you may need to run:

``` sh
sudo pip install -U es-stats-zabbix
```

To get the most recent version (0.1.2).

**Comment by gourlaa** [comment]
It's working !
Thanks.

**Comment by gourlaa** [comment]
I installed everything, and I still have a problem.

My agent is running, and my server is able to receive any data like :
pierre@br-monitoring:~$ zabbix_get -s 10.32.0.6 -p 10050 -k health[status]
0

However their is nothing in the interface of zabbix, maybe the template ?

**Comment by 4erpak** [comment]
I had this problem too :)
You should this sections
   "template  Elasticsearch Cluster /template"
   "name  Elasticsearch Cluster /name"
change to this one
<template>Template Elasticsearch Cluster</template>
and for all triggers
<expression>{Elasticsearch Cluster:health[status].last()}=2</expression>
change to this
<expression>{Template Elasticsearch Cluster:health[status].last()}=2</expression>

**Comment by untergeek** [comment]
Feel free to submit a PR for the 2.2 template with these changes (or export yours, with the changes).

**Comment by vTNT** [comment]
my zabbix servier also is 2.2 6,  i import es_stats_zabbix_template_2.2.xml. have this error: 
Cannot find value map "Exit Code" used for item "Cluster Stats Batch Run: $1" on "Elasticsearch Cluster".

**Comment by 4erpak** [comment]
Zabbix value maps

Create the following before importing the template:

ES Cluster State
0 ⇒ Green
1 ⇒ Yellow
2 ⇒ Red
Exit Code
0 ⇒ SUCCESS
1 ⇒ FAIL

**Comment by vTNT** [comment]
yes, thanks

**Comment by KaczynskiTed** [comment]
same problem with elastic version 2.4 and zabbix 3.0 LTS
